### ISSUE TITLE
Congrats on your new olkb keyboard!

### ISSUE THREAD

**Issue by algj** [EmeraldSnorlax/preonic#1]
Can't find you on discord, so just saying it here

How long have you been using it? Also, workman layout!? That is pretty cool!

Btw, my discord: `@alg#0001`

I hope you're doing fine

Also, I'm learning svelte(kit), it's mindblowing to me haha, why haven't I started using earlier?

**Comment by EmeraldSnorlax** [comment]
conversation moved to discord, check your frs
